import type { LibraryObject } from './types'

export const localLibraryObjects: LibraryObject[] = [
  {
    id: 'aai-carteira-cliente',
    title: 'Analise a carteira do meu cliente',
    description: 'Primeira consulta guiada para assessor entender concentração, riscos, eventos e pontos de conversa com cliente.',
    profiles: ['Assessor de Investimentos', 'AAI'],
    objectives: ['Atendimento', 'Carteira', 'Acompanhamento'],
    channels: ['MCP ChatGPT', 'Biblioteca'],
    objectType: 'Workflow',
    difficulty: 'Iniciante',
    requiredProducts: ['MCP'],
    requiredData: ['Carteira', 'Preços', 'Fundamentos', 'Notícias'],
    firstAction: 'Conectar MCP no ChatGPT e pedir a análise da carteira.',
    firstPrompt: 'Analise a carteira do meu cliente',
    expectedOutput: 'Resumo simples com concentração, riscos, notícias, eventos e próximos passos para conversa.',
    cta: 'Abrir tutorial ChatGPT',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 1,
  },
  {
    id: 'aai-copiloto-ligacao',
    title: 'Copiloto de ligação com cliente',
    description: 'Roteiro para preparar, conduzir e registrar uma conversa usando carteira, ativos e eventos relevantes.',
    profiles: ['Assessor de Investimentos', 'AAI', 'Comercial'],
    objectives: ['Atendimento', 'Preparação de ligação'],
    channels: ['MCP ChatGPT', 'Workspace'],
    objectType: 'Modelo de atendimento',
    difficulty: 'Iniciante',
    requiredProducts: ['MCP'],
    requiredData: ['Carteira', 'Notícias', 'Eventos'],
    firstAction: 'Selecionar cliente, revisar carteira e abrir roteiro de conversa.',
    firstPrompt: 'Prepare uma ligação com meu cliente considerando carteira, notícias e eventos do dia.',
    expectedOutput: 'Roteiro de ligação com abertura, pontos de atenção, perguntas e próximos passos.',
    cta: 'Usar roteiro',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 2,
  },
  {
    id: 'eventos-dia',
    title: 'Notícias e eventos do dia',
    description: 'Resumo diário dos fatos que podem impactar carteiras, conversas comerciais e acompanhamento de mercado.',
    profiles: ['Assessor de Investimentos', 'AAI', 'Trader', 'Gestor', 'Analista buy-side', 'Analista sell-side'],
    objectives: ['Monitoramento', 'Agenda', 'Notícias'],
    channels: ['MCP ChatGPT', 'MCP Claude', 'Terminal', 'Workspace'],
    objectType: 'Prompt',
    difficulty: 'Iniciante',
    requiredProducts: ['MCP', 'Terminal'],
    requiredData: ['Notícias', 'Calendário', 'Preços'],
    firstAction: 'Abrir o resumo do dia antes da primeira conversa ou decisão.',
    firstPrompt: 'Mostre as notícias e eventos do dia que podem impactar minha carteira.',
    expectedOutput: 'Lista priorizada de eventos, notícias, ativos impactados e pontos de atenção.',
    cta: 'Ver eventos do dia',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 3,
  },
  {
    id: 'dev-api-sandbox-curl',
    title: 'Primeira chamada API sandbox',
    description: 'Rota curta para gerar chave sandbox, copiar curl e validar resposta limitada sem liberar produção.',
    profiles: ['Desenvolvedor / Engenharia', 'Head de Tecnologia', 'Quant', 'Lead técnico'],
    objectives: ['Dados e integração', 'API sandbox'],
    channels: ['API sandbox', 'Workspace'],
    objectType: 'Template API',
    difficulty: 'Técnico',
    requiredProducts: ['API sandbox'],
    requiredData: ['Fundamentos', 'Preços'],
    firstAction: 'Gerar chave sandbox e copiar curl de fundamentos.',
    firstPrompt: 'Copie o exemplo curl e valide o payload de fundamentos.',
    expectedOutput: 'Primeira resposta da API com payload e limites claros.',
    cta: 'Gerar chave sandbox',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 1,
  },
  {
    id: 'trader-watchlist-terminal',
    title: 'Watchlist inicial no Terminal',
    description: 'Checklist para criar watchlist, acompanhar cotações, notícias e eventos relevantes no Terminal.',
    profiles: ['Trader', 'Gestor', 'Portfolio Manager'],
    objectives: ['Mercado', 'Monitoramento', 'Terminal'],
    channels: ['Terminal', 'Biblioteca'],
    objectType: 'Checklist Terminal',
    difficulty: 'Iniciante',
    requiredProducts: ['Terminal Economatica'],
    requiredData: ['Preços', 'Notícias', 'Calendário'],
    firstAction: 'Abrir Terminal e criar uma watchlist com ativos prioritários.',
    firstPrompt: 'Monte uma watchlist inicial com ativos, notícias e eventos relevantes.',
    expectedOutput: 'Watchlist configurada e rotina de acompanhamento do primeiro dia.',
    cta: 'Abrir Terminal',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 1,
  },
  {
    id: 'gestor-acompanhamento-carteira',
    title: 'Modelo de acompanhamento de carteira',
    description: 'Modelo para acompanhar exposição, risco, eventos e ativos mais relevantes da carteira.',
    profiles: ['Gestor', 'Portfolio Manager', 'Analista buy-side'],
    objectives: ['Carteira', 'Risco', 'Eventos'],
    channels: ['Plataforma Economatica', 'Terminal', 'MCP Claude'],
    objectType: 'Modelo de análise',
    difficulty: 'Intermediário',
    requiredProducts: ['Plataforma Economatica', 'Terminal'],
    requiredData: ['Carteira', 'Fundamentos', 'Preços', 'Notícias'],
    firstAction: 'Abrir modelo e selecionar carteira ou ativos prioritários.',
    firstPrompt: 'Faça um acompanhamento da carteira com exposição, riscos e eventos relevantes.',
    expectedOutput: 'Quadro de acompanhamento com risco, concentração, eventos e próximos pontos de análise.',
    cta: 'Abrir modelo',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 2,
  },
  {
    id: 'analista-modelo-empresa',
    title: 'Modelo de análise de empresa',
    description: 'Estrutura para analisar fundamentos, pares, notícias, eventos e próximos pontos de investigação.',
    profiles: ['Analista buy-side', 'Analista sell-side', 'Gestor'],
    objectives: ['Research', 'Fundamentos', 'Comparação'],
    channels: ['Plataforma Economatica', 'Terminal', 'MCP Claude'],
    objectType: 'Modelo de análise',
    difficulty: 'Intermediário',
    requiredProducts: ['Plataforma Economatica'],
    requiredData: ['Fundamentos', 'Notícias', 'Calendário'],
    firstAction: 'Selecionar empresa e abrir modelo de análise.',
    firstPrompt: 'Analise esta empresa com fundamentos, pares, notícias e eventos relevantes.',
    expectedOutput: 'Resumo estruturado com indicadores, comparação, eventos e pontos de atenção.',
    cta: 'Abrir modelo',
    source: 'Documentação técnica atual em produção',
    validationStatus: 'MVP inicial',
    priority: 2,
  },
];
